### ISSUE TITLE
유저 기능

### ISSUE THREAD

**Issue by saJaeHyukc** [1TEAM12/GaGgaMaGga_BE#1]
유저 기능에 들어갈 기능들 입니다.

- [x] 로그인 기능
- [x] 회원가입 기능 (이메일 인증)
- [x] 이메일 재인증 기능
- [x] 로그아웃 기능
- [x] 회원 비활성화 기능
- [x] 이메일 재인증 기능
- [x] 아이디 찾기 휴대폰 sms 발송 기능
- [x] 프로필 수정 기능
- [x] 개인프로필, 공개프로필 기능
- [x] 비밀번호 인증/ 비밀번호 변경 기능
- [x] 비밀번호 찾기 이메일 전송, 비밀번호 재설정 기능
- [x] 비밀번호 만료기간 지날 시 창 띄우는 기능
- [x] 최근 로그인 기록 볼 수 있는 기능
- [x] 소셜로그인 카카오톡(백엔드)
일단 헤더부분만 작성했습니다
- [x] 소셜로그인 카카오톡(프론트)
- [x] 비활성화가 되고 60일 지나면 메일보내고 삭제되는 기능
- [x] 회원정보 보유 기간 (1년이 지나면) 메일 보내주고 비활성화로 변경하는 기능
- [x] user부분 test코드 작성
- [x] 로그인 횟수 제한 기능(5번)
- [x] 어떤 ip로 접속했는지 확인하는 기능{추가기능}
- [x] 스웨거 적용

**Comment by JayJin** [comment]
유저기능 이슈 완료되어 close합니다.
- 로그인 기능
- 회원가입 기능 (이메일 인증)
- 이메일 재인증 기능
- 로그아웃 기능
- 회원 비활성화 기능
- 이메일 재인증 기능
- 아이디 찾기 휴대폰 sms 발송 기능
- 프로필 수정 기능
- 개인프로필, 공개프로필 기능
- 비밀번호 인증/ 비밀번호 변경 기능
- 비밀번호 찾기 이메일 전송, 비밀번호 재설정 기능
- 비밀번호 만료기간 지날 시 창 띄우는 기능
- 최근 로그인 기록 볼 수 있는 기능
- 소셜로그인 카카오톡(백엔드)
- 소셜로그인 카카오톡(프론트)
- 비활성화가 되고 60일 지나면 메일보내고 삭제되는 기능
- 회원정보 보유 기간 (1년이 지나면) 메일 보내주고 비활성화로 변경하는 기능
- user부분 test코드 작성
- 로그인 횟수 제한 기능(5번)
- 어떤 ip로 접속했는지 확인하는 기능{추가기능}
- 스웨거 적용

**Comment by saJaeHyukc** [comment]
성능 개선을 위해 오픈했습니다

- [ ] 이메일 전송속도 향상
- [ ] 공인 IP주소 파악

**Comment by saJaeHyukc** [comment]
요청이 들어왔을 때 그 ip가 공인 ip인지 또는 vpn인지 확인하는 방법을 알았습니다.
https://members.ip-api.com
이 api를 사용하여 알 수 있지만 매월 청구하는 금액이 있어서 여유가 안되어 
사용은 못하고 공공 api를 사용하여 최소한으로만 구현했습니다.
